#!/bin/bash

configure () {
    python3 -m venv venv
    source venv/bin/activate
    pip3 install -r requirements.txt
}

if [ "$1" = "configure" ]
then
    configure
else
    source venv/bin/activate
    python3 main.py ${@:1}
fi
